### ISSUE TITLE
Rename to "OpenFF Evaluator"

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-evaluator#175]
This issue tracks the progress of renaming this repo from "PropertyEstimator" to "(OpenFF)Evaluator"

**Comment by SimonBoothroyd** [comment]
My plan is to go for a repo name of 'openff-evaluator' and a module name of 'evaluator'.

**Comment by SimonBoothroyd** [comment]
The migration is target to start early next week once the issues surrounding the failing OSX tests have been resolved, and once the repo has been migrated to GitHub actions away from Travis.

**Comment by j-wags** [comment]
Sounds great. It'd be good to screenshare while we do this, so Monday or Tuesday next week would be great (I'm flying/at a conference W-F).

**Comment by SimonBoothroyd** [comment]
Working on this now - I'll make a post this in Slack likely early next week once the migration is fully finished and stable.

**Comment by SimonBoothroyd** [comment]
Things seem to have gone mostly smoothly. There were ~31 alerts introduced due to a bug on LGTM's end, but these should be resolved soon. I'm working through some of my slower integration tests now, but if they finish ok then I'll be aiming for a `openff-evaluator ==0.1.0` release next Monday.

I'll also I'm to have a ForceBalance PR ready by then to accommodate the changes.

**Comment by SimonBoothroyd** [comment]
Closing this issue as the migration is now complete.
