### ISSUE TITLE
Add calculation of excess molar volume

### ISSUE THREAD

**Issue by mrshirts** [openforcefield/openff-evaluator#282]
Although initial testing indicated that excess molar volume had sufficient numerical issues that made it not ideal for optimization (too noisy, needing substantial time to converge). I think it would be an important property to benchmark on going forward, especially since it is so straightforward to calculate (any simulation of heat of mixing can obtain the excess molar volume with no additional simulation work), and so should be included in the evaluator formalism.

It is also related to a key thermodynamic quantity. Partial molar volumes capture completely the combined pressure and component number response of the free energy, which is the fundamental function of interest, i.e.  V_i = d^2G/dPdN_i

Excess molar volumes are directly related to the partial molar volumes by V^E=\sum _i x_i (V _i-V_i^{ideal})
Where V_i^{ideal} is just the volume of pure i under those T and P conditions.

**Comment by ocmadin** [comment]
Initially, we haven't been looking at partial molar volume, but _excess_ molar volume, which has the issues that you described.  While we can get excess molar volumes from the same simulations as enthalpy of mixing, I don't think the same is true for partial molar volumes, since V_i = dV/dN_i, we'd essentially want to do finite difference at the concentration of interest, so to get an accurate result we couldn't just do the same simulations as enthalpy of mixing since those are typically pure A/pure B/mix AB, where the mix is usually 50/50 or 75/25.  Unless you have a different way of calculating partial molar volumes, I think we might need a new protocol for that quantity.

**Comment by mrshirts** [comment]
Hah, I am being stupid.  Yes, partial molar volume is harder to calculate since that's a differential quality.  The relationship between the the excess molar volume and the partial molar volume is:

V^E=\sum _i x_i (V _i-V_i^{ideal}) 

Where V_i^{ideal} is just the volume of pure i under those T and P conditions.

I'll update the main post.

**Comment by ocmadin** [comment]
Yeah, I think computing partial molar volumes may be quite noisy, given the small changes in composition and the sizes of the simulation boxes compared to continuum/macro. I'd imagine if we're having issues with noise in excess molar volume, that issue would be worse in partial molar volume.

**Comment by SimonBoothroyd** [comment]
@mrshirts thank you for clarifying your issue. Excess molar volumes are already supported by the framework [as documented here](https://openff-evaluator.readthedocs.io/en/property-documentation/properties/properties.html#excess-molar-volume).
