### ISSUE TITLE
Release plans

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-evaluator#447]
I'd like to gather some input for the next few releases of Evaluator.

With version 0.11.0 of the toolkit coming in a month or two, I intend to create a new line of Evaluator releases (starting at 0.4.0, based on https://github.com/openforcefield/openff-evaluator/pull/413) that are compatible with the new versions of the toolkit. These releases will **not** be compatible with older versions of the toolkit due to API differences. The timetable for this release is roughly at the same time as the full toolkit release. Once there are RC builds for the toolkit, I will be able to make pre-release packages of Evaluator.

For users that can't make this transition yet, I will maintain the 0.3.x line that is compatible with the "old" toolkit (0.10.x). This support will not last forever and is provided purely as a convenience to users while the transition to a fully-featured Interchange backend is underway.

Are there features not in the most recent release (https://github.com/openforcefield/openff-evaluator/releases/tag/v0.3.11) that people want in releases? The `master` branch is currently partway through this transition, but it's not hard to go back to a previous release tag and cherry-pick some number of PRs onto them. At the moment #426 is the only one I am aware of.

**Comment by j-wags** [comment]
Since we've committed to [moving evaluator to become the infrastructure team's responsibility](https://openforcefield.atlassian.net/wiki/spaces/IN/pages/1926070363/Infrastructure+Roadmap+2022+In+progress) in 2022, maybe this is the right time to formally do it. So I'll say "The infrastructure team takes responsibility for maintaining this repo, with @mattwthompson as primary maintainer". 

Note the difference between "maintaining" and "developing" - We're committed to maintaining this, and we'll review PRs, but this doesn't necessarily mean we'll accept all feature requests.

**Comment by mattwthompson** [comment]
Now that #413 is merged (and RC builds of the toolkit are up) I'll look to make a 0.4.0 RC soon.

**Comment by mattwthompson** [comment]
I'm making 0.4.0 today, which unfortunately [requires MDTraj 1.9.3 or 1.9.4](https://github.com/openforcefield/openff-evaluator/issues/470#issuecomment-1248878110).
