### ISSUE TITLE
Unit-related AttributeError on code which previously worked

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openff-evaluator#500]
I was previously using some code to build boxes with evaluator (overkill, I know) and it's currently failing with a unit-related AttributeError. Here's the code:

```
from openff.evaluator.protocols.coordinates import BuildCoordinatesPackmol
from openff.evaluator.substances import Substance, Component, MoleFraction, ExactAmount

substance = Substance()

substance.add_component(Component("Cc1ccccc1", role=Component.Role.Solvent), MoleFraction(0.1))
substance.add_component(Component("C1CCCCC1", role=Component.Role.Solvent), MoleFraction(0.9))
substance.add_component(Component("c1ccccc1O", role=Component.Role.Solute), ExactAmount(1))

coordinate_factory = BuildCoordinatesPackmol("")
coordinate_factory.substance = substance
coordinate_factory.max_molecules = 150
coordinate_factory.execute()

print("Your output file was written to:", coordinate_factory.coordinate_file_path)
```

I get `AttributeError: Neither Quantity object nor its magnitude (92.139036) has attribute 'unit'` from `coordinate_factory.execute()`.

I'm still using OpenMM 7.7. It's not obvious to me what the problem would be, since the tests (which are passing) seem to be calling `add_component` in an identical manner to what I'm doing here.

**Comment by davidlmobley** [comment]
Ah, sorry, this is the documented OpenMM-8 compatibility issue. Cross-posting from elsewhere: 

> (This will be documented in release notes and release assets - posting now as a heads-up) The current release of OpenFF Evaluator is not fully compatible with OpenMM 8. I hope to make the next release compatible with 7 and 8, but in the following release I intend to drop support for version 7. If this might cause you an issue please reach out.

**Comment by davidlmobley** [comment]
Actually, no, reopening, I have the same issue with OpenMM 8.

**Comment by mattwthompson** [comment]
What version are you using? I can't reproduce this with the past couple of releases or the current development head. The output of `conda list` would be great as well in case you have an unfortunate mix of older versions.

**Comment by mattwthompson** [comment]
Arg ... you're in an incompatible state that we weren't able to fully safeguard from. Evaluator 0.3.11 is not meant to work with Toolkit 0.11+; some of the packages were updated but due to quirks of how `conda-forge` is managed we can easily introduce constraints into new builds but it's harder to update the version constraints on existing builds.

![image](https://user-images.githubusercontent.com/7935382/219438484-1b4cb601-93ed-4ace-96fe-9131110caa3a.png)

You managed to luck into `py_blahblah_0` in your environment which is hard to work away from. In most cases the solver will prefer a newer build `py_blahblah_1` over one that's easier to find a solution for, but not always. (Notice the different toolkit requirements in these builds.) My guess is `mamba install "openff-evaluator >=0.4" -c conda-forge` or something similar should fix this up, and if you're shipping an environment YAML I'd recommend including that constraint there as well. Totally blowing up the environment may or may not work depending how it was set up, not sure.

**Comment by davidlmobley** [comment]
I can confirm that the recommended `mamba install...` does the trick. Thanks so much! (Not sure how I had ended up here, as I had `conda install evaluator...` yesterday before I ran into this problem, but, well, now it's working.
